### ISSUE TITLE
CTE's don't respond with JSON format

### ISSUE THREAD

**Issue by mike-luabase** [TimonKK/clickhouse#106]
Queries with a CTE respond with the data as text without the normal JSON structure
```
let sql = `
with a1 as (select 1)
select * from a1
`
const d = await clickhouse.query(sql).toPromise();
console.log('clickhouse result: ', d)
```

result
```
clickhouse result:  1  2
```

Using clickhouse-client

```
lua-2 :) with a1 as (select 1 as a)
         select a, 2 as b from a1

WITH a1 AS
    (
        SELECT 1 AS a
    )
SELECT
    a,
    2 AS b
FROM a1

Query id: e5d31289-c52c-425a-90f1-d87786ac8298

┌─a─┬─b─┐
│ 1 │ 2 │
└───┴───┘

1 rows in set. Elapsed: 0.133 sec. 
```

**Comment by mike-luabase** [comment]
ClickHouse client version 21.12.3.32 (official build).
Connecting to lua-2.luabase.altinity.cloud:9440 as user admin.
Connected to ClickHouse server version 21.12.3 revision 54452.

**Comment by mike-luabase** [comment]
As mentioned [here](https://github.com/TimonKK/clickhouse/issues/102), adding `with` to this regex appears to fix the issue

```
if (query.match(/^(select|with|show|exists)/i)) {
```

**Comment by TimonKK** [comment]
The fix has been released
