### ISSUE TITLE
Database options

### ISSUE THREAD

**Issue by xcHades** [TimonKK/clickhouse#13]
Hello!
Can you add the "database" option to specify a database? It should not be a hard issue, just one additional query parameter like `http://host:port/?database=my_db&query=...`.

**Comment by TimonKK** [comment]
Hello!
You mean like this:
```js
const ch = new ClickHouse({
 database: 'my_db'
});

// This query will be 'SELECT * FROM my_db.table1'
const rows = await ch.query('SELECT * FROM table1').toPromise();
```
?

**Comment by xcHades** [comment]
Yes, that's what I mean!

**Comment by TimonKK** [comment]
You can use like this:
```js
const ch = new ClickHouse({
	config : {
		database: 'my_db'
	}
});
```
