### ISSUE TITLE
Query string in request body

### ISSUE THREAD

**Issue by xcHades** [TimonKK/clickhouse#17]
Hello! I have queries with nested queries and with long where statements. And package fails this  queries because "query" parameter in http request is to long. Can you move sql query string from http query parameter to request body?

**Comment by TimonKK** [comment]
Hi,
Can you share your code?

**Comment by xcHades** [comment]
Something like that:
```javascript
for (let i = 0; i < array.length; i++) {
        queries.push(`SELECT ${array[i].Id} AS Id,
        toInt64(coalesce(
        (
            SELECT count()
            FROM table1
            WHERE (Column1 = ${array[i].Field1}) AND (Column2 = ${array[i].Field2})
        ), 0) + coalesce(
        (
            SELECT count()
            FROM table2
            WHERE (Column1 = ${array[i].Field1}) AND (Column2 = ${array[i].Field2})
        ), 0))`);
    }
    ch.query(queries.join(' UNION ALL '), callback);
```
It's quite far from best practices, but it's the fastest and simplest way to extract required data. So I hope to solve that problem without changing DB structure.

**Comment by TimonKK** [comment]
You can try rewrite your sql like this:
```sql
SELECT
    countIf(
       (Column1 = 11) AND (Column2 = 12) 
    ) AS 1_id,
    countIf(
       (Column1 = 21) AND (Column2 = 22) 
    ) AS 2_id,
   ...
FROM (
    SELECT
        *
    FROM table1
    UNION ALL
    SELECT
        *
    FROM table2
)
```

**Comment by xcHades** [comment]
It works great, thank you! I hope that this query will not break with a large number of countIf statements...

**Comment by TimonKK** [comment]
I use the query like this with 3 000 countIf and it works!
