### ISSUE TITLE
Error for query "EXISTS"

### ISSUE THREAD

**Issue by smoulderme** [TimonKK/clickhouse#20]
This is the query that executes with an error: 
```
EXISTS test_db.myTable
```

Current output:
```
undefined
```

Expected output:
```
0 or 1
```

I can execute this query over http protocol:
```
$ curl 'http://localhost:8123/?password=MyPassword&query=EXISTS%20test_db.myTable1'
0

$ curl 'http://localhost:8123/?password=MyPassword&query=EXISTS%20test_db.myTable'
1
```

**Comment by TimonKK** [comment]
Publish [fix](https://github.com/TimonKK/clickhouse/commit/5f51bfa48a5e97aaa3e623483a8a0ae091b88e00)
