### ISSUE TITLE
lodash vulnerability before 4.17.12

### ISSUE THREAD

**Issue by iWedmak** [TimonKK/clickhouse#24]
did you know that npm package of clickhouse have dependency of lodash with  vulnerability 
https://www.npmjs.com/advisories/1065
and if i fix it package breaks and i get 
UnhandledPromiseRejectionWarning: Error: Invalid protocol: clickhouse:

**Comment by ichhim** [comment]
I have submit PR for this one. #25

**Comment by ichhim** [comment]
@TimonKK Can you make a release of 1.2.21 on npm?

**Comment by TimonKK** [comment]
Done https://www.npmjs.com/package/clickhouse/v/1.2.21 !

**Comment by ichhim** [comment]
@TimonKK Nice, thank you.
