### ISSUE TITLE
Error for query "DROP TABLE [db.name]"

### ISSUE THREAD

**Issue by sovetkin-am** [TimonKK/clickhouse#3]
Hello!

It is necessary to correct the condition:

```
if ( ! opts.query.match(/^insert/i) && (!opts.query.match(/^create/i))) {
  opts.query += ' FORMAT TabSeparatedWithNamesAndTypes';
}
```

At least so:

```
if ( ! opts.query.match(/^insert/i) && (!opts.query.match(/^create/i)) && (!opts.query.match(/^drop/i))) {
  opts.query += ' FORMAT TabSeparatedWithNamesAndTypes';
}
```

**Comment by TimonKK** [comment]
Hi!I added you fix into npm package07.03.2017, 18:46, "Andrew Sovetkin" <notifications@github.com>:Hello!
It is necessary to correct the condition:
if ( ! opts.query.match(/^insert/i) && (!opts.query.match(/^create/i))) {
  opts.query += ' FORMAT TabSeparatedWithNamesAndTypes';
}

At least so:
if ( ! opts.query.match(/^insert/i) && (!opts.query.match(/^create/i)) && (!opts.query.match(/^drop/i))) {
  opts.query += ' FORMAT TabSeparatedWithNamesAndTypes';
}
