### ISSUE TITLE
sir,is there a method for bulk insert?

### ISSUE THREAD

**Issue by 564064202** [TimonKK/clickhouse#30]
sir,is there a method for bulk insert?

**Comment by TimonKK** [comment]
Hi,
Yes, exists two ways for this:
1. https://github.com/TimonKK/clickhouse/blob/master/test/test.js#L402
2. https://github.com/TimonKK/clickhouse/blob/master/test/test.js#L439
And you should remember abount https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-max_insert_block_size
if you insert is overflow max_insert_block_size
