### ISSUE TITLE
add tuples in ws

### ISSUE THREAD

**Issue by neyy91** [TimonKK/clickhouse#31]
Hello. How insert to CH tuple int-s in ws?
There is no description and examples in the documentation
for example
tuple (1,2,3)

example query

`CREATE TABLE visits ( id UInt64, test Tuple(UInt8, UInt8, UInt8) ) ENGINE = MergeTree()  PRIMARY KEY id  ORDER BY id;`

simple insert
 `INSERT INTO test.visits VALUES (1, (10,11,12));`

insert in ws
`
 const wsCH = clickhouse.insert('INSERT INTO test.visits').stream();
for (let i = 1; i <= 5; i++) {
  await wsCH.writeRow(
    [
      i, (10,11,12)
    ]
  );

  }

  const result = await wsCH.exec();
`

**Comment by neyy91** [comment]
but in the source code I find comment
index.js,  91 row

`// TODO: tuples support`
`if (!format) {`
`console.trace ();`
`}`

you're gonna fix it?)

**Comment by TimonKK** [comment]
Hi,
Yes, code doesnt support tuple, but you can add this functionality
