### ISSUE TITLE
what's output_format_json_quote_64bit_integers =1

### ISSUE THREAD

**Issue by 564064202** [TimonKK/clickhouse#33]
what's output_format_json_quote_64bit_integers =1,
what's output_format_json_quote_64bit_integers =0

**Comment by TimonKK** [comment]
It is [setting](https://clickhouse.yandex/docs/en/operations/settings/settings/#session_settings-output_format_json_quote_64bit_integers) of Clickhouse

**Comment by 564064202** [comment]
thanks
