### ISSUE TITLE
Question: Does it handle SQL injection?

### ISSUE THREAD

**Issue by sonirico** [TimonKK/clickhouse#37]

**Comment by TimonKK** [comment]
No, you must escape data before SQL query

**Comment by tobia** [comment]
Is there a function or an external library that can encode strings for Clickhouse SQL?

**Comment by TimonKK** [comment]
You can try to use [this](https://github.com/mysqljs/mysql#escaping-query-values)

**Comment by tobia** [comment]
[Here](https://clickhouse.tech/docs/en/sql-reference/syntax/#syntax-string-literal) it says:

> In string literals, you need to escape at least ' and \.

So maybe adding backslashes in front of `'` and `\` should be enough?

```javascript
function escape(value) {
  switch (typeof value) {
    case 'number':
      return value.toString()
    case 'string':
      return "'" + value.replace(/(?=['\\])/g, '\\') + "'"
    case 'boolean':
      return value ? '1' : '0'
    default:
      throw new Exception(`escape(${typeof value}) not implemented`)
  }
}

const assert = require('assert').strict
assert.equal(escape(""), "''")
assert.equal(escape("'"), "'\\''")
assert.equal(escape("\\"), "'\\\\'")
assert.equal(escape("a'\\b\\'c"), "'a\\'\\\\b\\\\\\'c'")
assert.equal(escape(3.14), "3.14")
assert.equal(escape(true), "1")
assert.equal(escape(false), "0")
```

If so, would you consider adding it as an utility?

**Comment by sonirico** [comment]
@tobia the best I found so far: https://www.npmjs.com/package/sqlstring
