### ISSUE TITLE
The `database` option: why undocumented?

### ISSUE THREAD

**Issue by do-** [TimonKK/clickhouse#39]
TimonKK,

Please mention the `database` option (see https://github.com/TimonKK/clickhouse/issues/13) in the README file.

Thanks in advance.

**Comment by TimonKK** [comment]
Done [it](https://github.com/TimonKK/clickhouse/commit/05f46b49b2be13d681aa0ad4bed9bf1262d3dbe9#diff-04c6e90faac2675aa89e2176d2eec7d8)
