### ISSUE TITLE
Create Datetime DEFAULT now()

### ISSUE THREAD

**Issue by Carlosbergx2** [TimonKK/clickhouse#41]
Hi I have tried to create a column default DateTime now()
and is not working properly.

Currently, I have:

```
`CREATE TABLE IF NOT EXISTS session_temp (
		ClientID UUID,
		FirstName String,
		Address String,
		City String,
		StartDate DateTime DEFAULT now()
	) ENGINE = MergeTree()
	PRIMARY KEY ClientID 
	ORDER BY ClientID`,
```

and
 ```
const insertSession = await clickhouseClient
    .insert(insertIntoTableByName('session_temp'))
    .stream();


 await insertSession.writeRow([
    uuid(),
    'firstname1',
    'address1',
    'city1',
  ]);

  await insertSession.exec();
```

it's firing an error, but if I inserted date after 'city' it works

Can someone help me ?
Thanks in advance
Carlos Vieira

**Comment by TimonKK** [comment]
I reproduced this error. But I don't know why we get error which I descibed into [issue](https://github.com/ClickHouse/ClickHouse/issues/9096)
