### ISSUE TITLE
fix: hide console log with me.isDebug flag

### ISSUE THREAD

**Issue by EndyKaufman** [TimonKK/clickhouse#42]
https://github.com/TimonKK/clickhouse/blob/d0d19ca18e2035f84d7d29f4785afdc2c274e104/index.js#L352

**Comment by TimonKK** [comment]
Thinks for feedback, [fixed](https://github.com/TimonKK/clickhouse/commit/21184333229bbf077b3cd2ad105da9b4977ce948)
