### ISSUE TITLE
How to return supplemental information in JSONCompact or JSON formats 

### ISSUE THREAD

**Issue by hatrena** [TimonKK/clickhouse#49]
Using `FORMAT JSON` or `FORMAT JSONCompact` only return the actual `data`. Is there any way to export `meta`, `data`, `extremes`, `rows`, etc as well? like the output in https://clickhouse.tech/docs/en/interfaces/formats/#jsoncompact?

**Comment by TimonKK** [comment]
Query with "FORMAT JSON":
```js
const LIMIT_COUNT = 10;	
		const result = await clickhouse.query(`
			SELECT
				rowNumberInAllBlocks() AS i,
				SUM(number)
			FROM (
				SELECT
					number
				FROM
					system.numbers
				LIMIT 1000
			)
			GROUP BY i WITH TOTALS
			LIMIT ${LIMIT_COUNT}
			FORMAT JSON
		`).toPromise();
```
works well:
```js
{ meta:
   [ { name: 'i', type: 'UInt64' },
     { name: 'SUM(number)', type: 'UInt64' } ],
  data:
   [ { i: 0, 'SUM(number)': 0 },
     { i: 610, 'SUM(number)': 610 },
     { i: 720, 'SUM(number)': 720 },
     { i: 948, 'SUM(number)': 948 },
     { i: 774, 'SUM(number)': 774 },
     { i: 462, 'SUM(number)': 462 },
     { i: 380, 'SUM(number)': 380 },
     { i: 24, 'SUM(number)': 24 },
     { i: 170, 'SUM(number)': 170 },
     { i: 192, 'SUM(number)': 192 } ],
  totals: { i: 0, 'SUM(number)': 499500 },
  rows: 10,
  statistics: { elapsed: 0.000461374, rows_read: 1000, bytes_read: 8000 } }
```
Why you want use FORMAT options? By default driver use JSONEachRow which work perfectly

**Comment by hatrena** [comment]
I am sorry that I did not provide any sample queries. I need the exact result (with `rows_before_limit_at_least`) you provided in a condition that there is no `GROUP BY`. 

According to ClickHouse: https://clickhouse-docs.readthedocs.io/en/latest/formats/json.html
`rows_before_limit_at_least` - The minimal number of rows there would have been without a LIMIT. Output only if the query contains LIMIT.

If the query contains `GROUP BY`, `rows_before_limit_at_least` is the exact number of rows there would have been without a `LIMIT`.

So I need to have `rows_before_limit_at_least` without using `GROUP BY`. In your example, If i want no `GROUP BY`, the query would be like:

```
SELECT
  rowNumberInAllBlocks() AS i,
  number
FROM (
  SELECT
    number
  FROM
    system.numbers
  LIMIT 1000
)
LIMIT 100
FORMAT JSON
```
The result of this query would be only the actual data, and not the supplemental like `rows`, `statistics`  and `rows_before_limit_at_least` as well.

**Comment by TimonKK** [comment]
You can use code like this:
```js
		const result = await clickhouse.query(`
			SELECT
			  rowNumberInAllBlocks() AS i,
			  number
			FROM (
			  SELECT
			    number
			  FROM
			    system.numbers
			  LIMIT 1000
			)
			LIMIT ${LIMIT_COUNT}
			FORMAT JSON
		`).withTotals().toPromise();
```

**Comment by hatrena** [comment]
Perfect, that was helpful :)
