### ISSUE TITLE
possible custom Session ID with each query

### ISSUE THREAD

**Issue by sarthaksahni** [TimonKK/clickhouse#50]
Is it possible to send custom `session_id` with each query, it can allow us to create separate sessions for each client on request basis. Currently the `session_id` is the one created while connecting. Once connected it cannot change, however we send it explicitly in each HTTP Request, just confirmed it in debug mode. 

If this is not possible, can it be done? It's a minor change because we are already using `me.opts.config` in each request, we can just extend the object with a third parameter in `_getReqParams(query, data)`

**Comment by TimonKK** [comment]
You need parallel query with own session? Or you need pass some specific session_id in each query?

**Comment by sarthaksahni** [comment]
`You need parallel query with own session` --- This is not possible by the design of ClickHouse. If it is I would love to know. 

`you need pass some specific session_id in each query?` -- __YES! Exactly!__

**Comment by sarthaksahni** [comment]
added a PR #52 for the same as well. Please let me know if I am doing something fundamentally wrong here.

**Comment by sarthaksahni** [comment]
Just checked the test are added by you at [line 300](https://github.com/TimonKK/clickhouse/blob/master/test/test.js#L300), thanks for looking into the issue however this is not what I meant, as we all know in JS most of the variables are referred apart from numbers and some other.. so the issue is that the same ClickHouse connection is used across multiple routes and connections and requests that are served by the http server at node as well! Now due to same session name the queries will get locked!

But I am sure this was taken care and random sessions are created, however this defeats the purpose of creating a temporary table and serving user the data from this temporary table to prevent further querying the main table over which we won't like to put stress on! 

__Use Case__
I have a complex query that consumes a lot of time, and I simply create a session for one of my user and provide a session id such as `sess_${userId}` now when this user queries I would use this session_id to access the temporary table I built for this specific user in the specific session. 

This can enable people using this driver to create destroy and persist session as per the requirement. 

_(PS: I upgraded from 19.6 to 20.3 as I got to know about fixed session locking issues, but they still persist, concurrent HTTP calls lock session. I am shifting my code base to build actual memory engine tables and then destroying them over the time by analysing `system.tables`, hope our discussion helps someone else.)_

**Comment by TimonKK** [comment]
Do you mean interface like this:
```js
// init
const clickhouse = new ClickHouse(...);

// route
const userCH = clickhouse.getSession();
const rows = await userCH.quiery...
const rows2 = await userCH.query...
?

**Comment by dws-sarthak** [comment]
Possibly yes, that's another way to put it, in short isolating one request and session name. However, if `User A` sends me a request, I would like to create a session as `session_user_a` and for `User B` I would create `sess_user_b` and ensure they don't lock each other out at any point in time.

**Comment by sarthaksahni** [comment]
Possibly yes, that's another way to put it, in short _isolating one request and session name_. However, if `User A` sends me a request, I would like to create a session as `session_user_a` and for `User B` I would create `sess_user_b` and ensure _they don't lock each other out_ at any point in time.

**Comment by TimonKK** [comment]
I published [version](https://www.npmjs.com/package/clickhouse) with your MR

**Comment by sarthaksahni** [comment]
Thanks a ton!
