### ISSUE TITLE
How to provide SSL CA file path?

### ISSUE THREAD

**Issue by serg-kan** [TimonKK/clickhouse#55]
Hello

Could you please help me with providing sslCA file to configuration?
Is it possible and if it is, how the field is named and where to put it?

thank you

**Comment by TimonKK** [comment]
Hi,
you can use [this](https://github.com/TimonKK/clickhouse/blob/master/test/test.js#L404)

**Comment by nleo** [comment]
```js
function init(opts) {
    return new ClickHouse({
        url: `https://${opts.host}`,
        port: 8443,
        database: opts.database,
        basicAuth: {
          username: opts.user,
          password: opts.password,
        },
        reqParams: {
          ca: fs.readFileSync('ca.pem')
        },
      })
}
```

**Comment by TimonKK** [comment]
Your example has missed `agentOptions` into `reqParams`. Or what do you mean?

**Comment by nleo** [comment]
@TimonKK I use it in prod somehow ¯ \ _ (ツ) _ / ¯

**Comment by TimonKK** [comment]
If you comment `reqParams` in your config then you will get error like 'connection reset' ?
