### ISSUE TITLE
Update clause supported

### ISSUE THREAD

**Issue by sliontc** [TimonKK/clickhouse#57]
Does the library support update clause?

**Comment by TimonKK** [comment]
You can use **query** method:
```js
await clickhouse.query('ALTER TABLE table UPDATE column1 = expr1 WHERE filter_expr').exec();
```
with query from [docs](https://clickhouse.tech/docs/en/sql-reference/statements/alter/update/)

**Comment by sliontc** [comment]
Thanks. I will try.
