### ISSUE TITLE
external doesn't work

### ISSUE THREAD

**Issue by shlomi-ozon** [TimonKK/clickhouse#58]
Hi, 
I am trying to use "external" with the query and it is not working.
after a minute I get a timeout message.
I guess the issue is from the sending because I tried to use the same query as in the example (very simple query with data in length of 10 short strings).
how can I fix it?
and by the way, I noticed that the URL for the request include the format of tabSeparateWithNames while I sending the structure not in the data itself (sent it as structure key in the external object ), it is not going to ignore my first data raw because of it?

this is the URL when I tried to run the test query:
http://************/?user=default&session_timeout=100&output_format_json_quote_64bit_integers=0&enable_http_compression=true&query_id=772f1903-389d-469e-9736-b9d1ccbe0698&database=default&temp_table_structure=str+String&query=SELECT+count%28*%29+AS+count+FROM+temp_table

**Comment by TimonKK** [comment]
Can you post js-code with example of query?

**Comment by shlomi-ozon** [comment]
For testing i used the same code as the test in the test file.
```
const rows = await CH.query('SELECT * AS count FROM temp_table', {
    external: [
        {
            name: 'temp_table',
            data: _.range(0, 15).map((i) => `str${i}`)
        },
    ]
}).toPromise();
```

this is the error I get after some time:
(node:55749) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT .********(server ip)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
