### ISSUE TITLE
Support insert data with `FORMAT JSONEachRow`

### ISSUE THREAD

**Issue by dangxuanhung** [TimonKK/clickhouse#60]
For now, default FORMAT when inserting data is `TabSeparated`, Can you please support `JSONEachRow` or have a way to disable auto append `FORMAT TabSeparated`?

https://github.com/TimonKK/clickhouse/blob/90baf55873590a692e80c05609993c5430e95dc8/index.js#L511 

Thank you

**Comment by pavhov** [comment]
Hello @dangxuanhung in config parameter I am added format: "json", // "json" || "csv" || "tsv" property 

you can change this property one of these values 

this merge request is not current.

in the example there is an example please be careful

![image](https://user-images.githubusercontent.com/8784893/107408950-0febb680-6b25-11eb-8918-e1791a949dd9.png)

**Comment by dangxuanhung** [comment]
Thanks @pavhov

**Comment by pavhov** [comment]
Welcome @dangxuanhung
